Repository beyond-all-reason/RecoilEngine, pull requests merged in 2024-12, with the labels that each got.

#1794 Add /debugquadfield to draw quadfield related information (v2).
  doc/site/_data/unsynced_commands.json
  rts/Game/UnsyncedGameCommands.cpp
  rts/Rendering/CMakeLists.txt
  rts/Rendering/DebugDrawerQuadField.cpp
  rts/Rendering/DebugDrawerQuadField.h
Labels: debugtools

#1791 Annotate our NIH flat_set for the future
  rts/System/ContainerUtil.h
Labels: refactor

#1793 Fontconfig: Make init and teardown more robust.
  rts/Rendering/Fonts/CFontTexture.cpp
  rts/Rendering/Fonts/CFontTexture.h
  rts/System/SpringApp.cpp
Labels: fonts

#1809 Fontconfig windows workaround v2
  rts/Rendering/Fonts/CFontTexture.cpp
Labels: fonts

#1813 Allow negative index at GetUnitCurrentCommand to index from queue end.
  rts/Lua/LuaConstEngine.cpp
  rts/Lua/LuaSyncedRead.cpp
Labels: Lua API

#1805 Stablize sorts used by path finders
  rts/Sim/Path/HAPFS/PathDataTypes.h
  rts/Sim/Path/QTPFS/PathThreads.h
Labels: candidate

#1806 Don't preload glyphs for non-alphanumeric fonts.
  rts/Rendering/Fonts/CFontTexture.cpp
Labels: fonts

#1811 Apply radar error to lua spatial queries.
  rts/Lua/LuaSyncedRead.cpp
Labels: bug

#1814 Add Spring.GetUnitCommandCount for getting a units command queue count.
  rts/Lua/LuaSyncedRead.cpp
  rts/Lua/LuaSyncedRead.h
Labels: Lua API

#1198 Tracy zones2 Add further once-per-frame zones, colorize top-level zones consistently
  rts/Game/GameHelper.cpp
  rts/Game/UI/MiniMap.cpp
  rts/Rendering/Env/Particles/ProjectileDrawer.cpp
  rts/Sim/Projectiles/ProjectileHandler.cpp
  rts/Sim/Units/UnitHandler.cpp
Labels: candidate

#1790 Fallback fonts with atlas clearing.
  cont/LuaUI/callins.lua
  cont/LuaUI/widgets.lua
  cont/base/springcontent/LuaGadgets/callins.lua
  cont/base/springcontent/LuaGadgets/gadgets.lua
  rts/Lua/LuaFonts.cpp
  rts/Lua/LuaFonts.h
  rts/Lua/LuaHandle.cpp
  rts/Lua/LuaHandle.h
  rts/Rendering/Fonts/CFontTexture.cpp
  rts/Rendering/Fonts/CFontTexture.h
  rts/System/EventClient.h
  rts/System/EventHandler.cpp
  rts/System/EventHandler.h
  rts/System/Events.def
Labels: fonts

#1761 RmlUI Context handling improvements
  rts/Rml/Backends/RmlUi_Backend.cpp
  rts/Rml/Backends/RmlUi_Backend.h
  rts/Rml/SolLua/bind/Global.cpp
Labels: bug, candidate

#1651 Add `tracy.LuaTracyPlot` and `tracy.LuaTracyPlotConfig`
  rts/Lua/CMakeLists.txt
  rts/Lua/LuaHandle.cpp
  rts/Lua/LuaParser.cpp
  rts/Lua/LuaTracyExtra.cpp
  rts/Lua/LuaTracyExtra.h
  rts/Lua/LuaUtils.cpp
  rts/Lua/LuaUtils.h
  rts/Lua/LuaVFS.cpp
Labels: Lua API, candidate

#1706 Add trace ray ground Lua functions
  rts/Lua/LuaSyncedRead.cpp
  rts/Lua/LuaSyncedRead.h
Labels: Lua API, candidate

#1729 Get rid of `CMD_AISELECT`
  rts/ExternalAI/AISCommands.cpp
  rts/ExternalAI/Interface/AISCommands.h
  rts/ExternalAI/SSkirmishAICallbackImpl.cpp
  rts/Lua/LuaConstCMD.cpp
  rts/Sim/Units/CommandAI/Command.h
  tools/DemoTool/DemoTool.cpp
Labels: refactor, candidate

#1838 Dollycam zero transition time
  rts/Game/Camera/DollyController.cpp
Labels: candidate

#1325 Reduce copy-paste in skirmish AI resource interface implementation
  rts/ExternalAI/SSkirmishAICallbackImpl.cpp
Labels: candidate

#1328 Tooltip resource packs + layout tweak
  rts/Game/UI/TooltipConsole.cpp
  rts/Game/UI/TooltipConsole.h
Labels: candidate

#1852 Make Cannon respect srcPos on HaveFreeLineOfFire.
  rts/Sim/Weapons/Cannon.cpp
Labels: bug, Lua API

#1858 Add Spring.SetProjectileTimeToLive.
  rts/Lua/LuaSyncedCtrl.cpp
  rts/Lua/LuaSyncedCtrl.h
  rts/Sim/Projectiles/WeaponProjectiles/WeaponProjectile.h
Labels: Lua API, candidate
