Repository beyond-all-reason/RecoilEngine, pull requests merged in 2025-05, with the labels that each got.

#1710 Fix docs for the select command
  doc/site/articles/select-command.markdown
Labels: area: documentation

#2269 Fonts textwrap prescan for glyphs
  rts/Rendering/Fonts/TextWrap.cpp
  rts/Rendering/Fonts/TextWrap.h
  rts/Rendering/Fonts/glFont.h
Labels: area: fonts

#2130 Mouse button binds.
  rts/Game/Game.cpp
  rts/Game/Game.h
  rts/Game/GameController.h
  rts/Game/UI/KeyCodes.cpp
  rts/Game/UI/KeyCodes.h
  rts/Game/UI/MouseHandler.cpp
  rts/Game/UI/MouseHandler.h
  rts/Game/UI/ScanCodes.cpp
  rts/Game/UI/ScanCodes.h
Labels: area: Input

#2276 Partial glyph shadow updates
  rts/Rendering/Fonts/CFontTexture.cpp
  rts/Rendering/Fonts/CFontTexture.h
  rts/Rendering/Textures/Bitmap.cpp
  rts/Rendering/Textures/Bitmap.h
Labels: area: fonts

#1752 Warnings cleanup
  rts/Net/AutohostInterface.cpp
Labels: status: candidate

#2219 Move LuaBitOps to LuaMathExtra
  rts/Lua/CMakeLists.txt
  rts/Lua/LuaBitOps.cpp
  rts/Lua/LuaBitOps.h
  rts/Lua/LuaHandle.cpp
  rts/Lua/LuaMathExtra.cpp
  rts/Lua/LuaMathExtra.h
Labels: refactor, status: candidate

#2304 Deprecate Spring.GetCommandQueue.
  rts/Lua/LuaSyncedRead.cpp
Labels: deprecation

#2289 Document registering AllowWeapon and Projectile callins.
  rts/Lua/LuaHandle.cpp
  rts/Lua/LuaHandleSynced.cpp
Labels: area: documentation

#2308 VFS.CalculateHash: Sha512 actually gets hex encoded.
  rts/Lua/LuaVFS.cpp
Labels: area: documentation

#2301 Document DrawScreenPost gotcha
  rts/Lua/LuaHandle.cpp
Labels: area: documentation

#2164 Mouse button binds. Part 2: Simple Input Receiver+middle button
  rts/Game/CMakeLists.txt
  rts/Game/Game.cpp
  rts/Game/Game.h
  rts/Game/GameController.h
  rts/Game/GameInputReceiver.cpp
  rts/Game/GameInputReceiver.h
  rts/Game/UI/MouseHandler.cpp
  rts/Game/UI/MouseHandler.h
Labels: area: Input

#2315 Allow tables inside SendToUnsynced.
  rts/Lua/LuaHandleSynced.cpp
Labels: area: Lua API

#2297 Lua debug module for synced when DevMode=1
  rts/Lua/LuaHandle.cpp
  rts/Lua/LuaHandle.h
  rts/Lua/LuaHandleSynced.cpp
  rts/Lua/LuaHandleSynced.h
Labels: area: Lua API

#2328 Document the wait commands.
  rts/Lua/LuaConstCMD.cpp
Labels: area: documentation

#2325 fonts: Allow disabling automatic setting of glBlendFunc
  rts/Lua/LuaFonts.cpp
  rts/Lua/LuaOpenGL.cpp
  rts/Rendering/Fonts/glFont.cpp
  rts/Rendering/Fonts/glFont.h
  rts/Rendering/Fonts/glFontRenderer.cpp
  rts/Rendering/Fonts/glFontRenderer.h
Labels: area: fonts
