Repository beyond-all-reason/RecoilEngine, pull requests merged in 2025-01, with the labels that each got.

#1867 Add waterbump_4tiles.dds to basecontent and use it as the default water.normalTexture
  cont/base/bitmaps/CMakeLists.txt
  cont/base/bitmaps/README.txt
  cont/base/bitmaps/bitmaps/waterbump_4tiles.dds
  rts/Map/MapInfo.cpp
Labels: enhancement, status: needs-testing

#1870 Add an article about yardmaps and map squares
  doc/site/articles/yardmaps.markdown
  doc/site/assets/guides/article-yardmap-solars-1.png
  doc/site/assets/guides/article-yardmap-solars-2.png
  doc/site/assets/guides/article-yardmap-solars-3.png
Labels: area: documentation, status: candidate

#1876 Fix dedicated's initial network timeout setting
  rts/Net/GameServer.cpp
  rts/builds/dedicated/main.cpp
Labels: status: candidate

#1822 Accept nil for params and options arguments for Spring.GiveOrder family functions.
  rts/Lua/LuaSyncedCtrl.cpp
  rts/Lua/LuaUtils.cpp
Labels: area: Lua API, status: candidate

#1847 Document what "synced" means in pathing
  rts/Sim/Path/QTPFS/Path.h
Labels: area: documentation, status: candidate

#1865 Document some build square assumptions
  rts/Game/Game.cpp
  rts/Game/GameHelper.cpp
  rts/Lua/LuaConstGame.cpp
  rts/Sim/Misc/GlobalConstants.h
Labels: status: candidate

#1871 `allowHoverUnitStrafing` modrule defaults to false
  rts/Sim/Misc/ModInfo.cpp
Labels: status: candidate

#1848 Add ActiveCommandChanged callin.
  cont/LuaUI/callins.lua
  cont/LuaUI/main.lua
  cont/LuaUI/widgets.lua
  cont/base/springcontent/LuaGadgets/callins.lua
  cont/base/springcontent/LuaGadgets/gadgets.lua
  rts/Game/UI/GuiHandler.cpp
  rts/Game/UI/GuiHandler.h
  rts/Lua/LuaHandle.cpp
  rts/Lua/LuaHandle.h
  rts/System/EventClient.cpp
  rts/System/EventClient.h
  rts/System/EventHandler.cpp
  rts/System/EventHandler.h
  rts/System/Events.def
Labels: area: Lua API, status: candidate

#1874 Put modrule checks at the end of modrule parsing
  rts/Sim/Misc/ModInfo.cpp
Labels: refactor, status: candidate

#1872 Update NETMSG_MAPDRAW to uint32 on both sides of serialization
  rts/Game/InMapDraw.cpp
  rts/Net/Protocol/BaseNetProtocol.cpp
  rts/Net/Protocol/BaseNetProtocol.h
  tools/DemoTool/DemoTool.cpp
Labels: status: candidate

#1857 Make missile weapons pass myGravity from weaponDef to projectiles.
  rts/Sim/Projectiles/WeaponProjectiles/MissileProjectile.cpp
  rts/Sim/Weapons/MissileLauncher.cpp
  rts/Sim/Weapons/WeaponDef.cpp
Labels: status: candidate

#1879 Lua frontend to allow changing unit's storage
  rts/Lua/LuaSyncedCtrl.cpp
  rts/Lua/LuaSyncedCtrl.h
  rts/Lua/LuaSyncedRead.cpp
  rts/Lua/LuaSyncedRead.h
Labels: area: Lua API, status: candidate

#1885 Add DEPRECATED Loglevel
  rts/Game/UI/KeySet.cpp
  rts/Lua/LuaSyncedRead.cpp
  rts/Lua/LuaUnsyncedCtrl.cpp
  rts/Lua/LuaUtils.cpp
  rts/System/Log/ConsoleSink.cpp
  rts/System/Log/ILog.h
  rts/System/Log/Level.h
  rts/System/Log/LogUtil.c
Labels: status: candidate

#1853 Add unit::noGroup and Get/SetUnitNoGroup
  cont/base/springcontent/LuaGadgets/Gadgets/unit_dead.lua
  rts/Game/UI/Groups/Group.cpp
  rts/Lua/LuaUnsyncedCtrl.cpp
  rts/Lua/LuaUnsyncedCtrl.h
  rts/Lua/LuaUnsyncedRead.cpp
  rts/Lua/LuaUnsyncedRead.h
  rts/Sim/Units/Unit.cpp
  rts/Sim/Units/Unit.h
Labels: status: candidate

#1850 Don't remove unit from groups on CUnit::ForcedKillUnit.
  rts/Sim/Units/Unit.cpp
Labels: status: candidate

#1882 Updating website mentions of recoil users
  doc/site/index.markdown
Labels: status: candidate

#1840 Platform: add totalRAM.
  rts/Lua/LuaConstPlatform.cpp
  rts/System/CMakeLists.txt
  rts/System/Platform/Hardware.h
  rts/System/Platform/Linux/Hardware.cpp
  rts/System/Platform/Misc.cpp
  rts/System/Platform/Win/Hardware.cpp
  rts/System/Platform/Win/WinVersion.cpp
  rts/builds/dedicated/CMakeLists.txt
  tools/DemoTool/CMakeLists.txt
  tools/unitsync/CMakeLists.txt
Labels: area: Lua API, status: candidate

#1844 Synced Lua pathing requests should not be batched and deferred.
  rts/Lua/LuaPathFinder.cpp
Labels: status: candidate
