Repository beyond-all-reason/RecoilEngine, pull requests merged in 2025-06, with the labels that each got.

#2165 Mouse button binds. Part 3: Game to InputReceiver refactor
  rts/Game/Game.cpp
  rts/Game/Game.h
  rts/Game/GameController.h
  rts/Game/GameInputReceiver.cpp
  rts/Game/GameInputReceiver.h
  rts/Game/UI/GuiHandler.cpp
  rts/Game/UI/MouseHandler.cpp
  rts/Lua/LuaHandle.cpp
Labels: area: Input

#2323 Fix bad goal performance spike
  rts/Sim/Path/QTPFS/PathSearch.cpp
Labels: area: Pathfinding

#2329 Make aircraft die on first contact with ground when crashing.
  rts/Sim/MoveTypes/HoverAirMoveType.cpp
  rts/Sim/MoveTypes/HoverAirMoveType.h
  rts/Sim/MoveTypes/StrafeAirMoveType.cpp
  rts/Sim/MoveTypes/StrafeAirMoveType.h
Labels: status: candidate-next

#1619 Remove uncollidable immobile kamikazes exception
  rts/Sim/Units/Unit.cpp
Labels: status: candidate-next

#2296 Lua base64 methods
  cont/LuaUI/system.lua
  cont/base/maphelper/maphelper/system.lua
  cont/base/springcontent/LuaGadgets/system.lua
  cont/base/springcontent/gamedata/system.lua
  rts/Lua/CMakeLists.txt
  rts/Lua/LuaEncoding.cpp
  rts/Lua/LuaEncoding.h
  rts/Lua/LuaHandle.cpp
  rts/Lua/LuaHandle.h
  rts/Lua/LuaHandleSynced.cpp
  rts/Lua/LuaIntro.cpp
  rts/Lua/LuaMenu.cpp
  rts/Lua/LuaParser.cpp
  rts/Lua/LuaUI.cpp
  rts/builds/dedicated/CMakeLists.txt
  tools/unitsync/CMakeLists.txt
Labels: area: Lua API, status: candidate-next

#2318 Allow to draw only selected side planes in CBitmapMuzzleFlame
  rts/Rendering/Env/Particles/Classes/BitmapMuzzleFlame.cpp
  rts/Rendering/Env/Particles/Classes/BitmapMuzzleFlame.h
  rts/Rendering/Env/Particles/Classes/SimpleParticleSystem.cpp
Labels: status: candidate-next

#2368 Lua Privileged Bytecode
  rts/Lua/LuaHandle.cpp
  rts/Lua/LuaHandle.h
  rts/Lua/LuaHandleSynced.cpp
  rts/Lua/LuaHandleSynced.h
  rts/Lua/LuaUI.cpp
  rts/lib/lua/CMakeLists.txt
  rts/lib/lua/include/lua_privileges.h
  rts/lib/lua/src/lapi.cpp
  rts/lib/lua/src/lauxlib.cpp
  rts/lib/lua/src/ldo.cpp
  rts/lib/lua/src/ldo.h
  rts/lib/lua/src/lua_privileges.cpp
Labels: area: Lua API

#1551 Fix #1537, redundant factory insert cancelling
  rts/Sim/Units/CommandAI/FactoryCAI.cpp
  rts/Sim/Units/CommandAI/FactoryCAI.h
  rts/Sim/Units/UnitTypes/Factory.cpp
  rts/Sim/Units/UnitTypes/Factory.h
Labels: status: candidate-next

#2375 Add mathextra methods to all lua environments.
  rts/Lua/LuaHandle.cpp
  rts/Lua/LuaParser.cpp
  rts/builds/dedicated/CMakeLists.txt
  tools/unitsync/CMakeLists.txt
Labels: area: Lua API

#2380 Add Spring.GetFactoryCommandCount for getting a factory queue count.
  rts/Lua/LuaSyncedRead.cpp
  rts/Lua/LuaSyncedRead.h
Labels: area: Lua API

#2113 Prevent rezbot from chasing unrepaired units in area resurrection
  rts/Sim/Units/CommandAI/BuilderCAI.cpp
  rts/Sim/Units/UnitTypes/Builder.cpp
Labels: status: candidate-next

#1831 Fix static ghost behaviours
  cont/base/springcontent/LuaGadgets/Gadgets/mobile_ghost_transport.lua
  rts/Lua/LuaSyncedCtrl.cpp
  rts/Lua/LuaSyncedCtrl.h
  rts/Lua/LuaSyncedRead.cpp
  rts/Lua/LuaSyncedRead.h
  rts/Lua/LuaUnitDefs.cpp
  rts/Rendering/Units/UnitDrawer.h
  rts/Rendering/Units/UnitDrawerData.cpp
  rts/Rendering/Units/UnitDrawerData.h
  rts/Sim/Units/Unit.cpp
  rts/Sim/Units/Unit.h
  rts/Sim/Units/UnitDef.cpp
  rts/Sim/Units/UnitDef.h
Labels: status: candidate-next

#2322 Multipage texture atlases, works with projectile and ground flash textures only for now
  cont/base/springcontent/shaders/GLSL/ProjFXFragProg.glsl
  cont/base/springcontent/shaders/GLSL/ProjFXFragShadowProg.glsl
  cont/base/springcontent/shaders/GLSL/ProjFXVertProg.glsl
  rts/Lua/LuaOpenGL.cpp
  rts/Rendering/CMakeLists.txt
  rts/Rendering/Env/BumpWater.cpp
  rts/Rendering/Env/Decals/GroundDecal.h
  rts/Rendering/Env/Decals/GroundDecalHandler.cpp
  rts/Rendering/Env/Particles/Classes/BitmapMuzzleFlame.cpp
  rts/Rendering/Env/Particles/Classes/BubbleProjectile.cpp
  rts/Rendering/Env/Particles/Classes/DirtProjectile.cpp
  rts/Rendering/Env/Particles/Classes/ExploSpikeProjectile.cpp
  rts/Rendering/Env/Particles/Classes/GeoSquareProjectile.cpp
  rts/Rendering/Env/Particles/Classes/HeatCloudProjectile.cpp
  rts/Rendering/Env/Particles/Classes/MuzzleFlame.cpp
  rts/Rendering/Env/Particles/Classes/NanoProjectile.cpp
  rts/Rendering/Env/Particles/Classes/RepulseGfx.cpp
  rts/Rendering/Env/Particles/Classes/ShieldSegmentProjectile.cpp
  rts/Rendering/Env/Particles/Classes/SimpleParticleSystem.cpp
  rts/Rendering/Env/Particles/Classes/SmokeProjectile.cpp
  rts/Rendering/Env/Particles/Classes/SmokeProjectile2.cpp
  rts/Rendering/Env/Particles/Classes/SmokeTrailProjectile.cpp
  rts/Rendering/Env/Particles/Classes/SpherePartProjectile.cpp
  rts/Rendering/Env/Particles/Classes/WakeProjectile.cpp
  rts/Rendering/Env/Particles/Classes/WreckProjectile.cpp
  rts/Rendering/Env/Particles/ProjectileDrawer.cpp
  rts/Rendering/Env/Particles/ProjectileDrawer.h
  rts/Rendering/Fonts/CFontTexture.cpp
  rts/Rendering/GroundFlash.cpp
  rts/Rendering/Textures/3DOTextureHandler.cpp
  rts/Rendering/Textures/3DOTextureHandler.h
  rts/Rendering/Textures/AtlasedTexture.cpp
  rts/Rendering/Textures/AtlasedTexture.hpp
  rts/Rendering/Textures/IAtlasAllocator.h
  rts/Rendering/Textures/LegacyAtlasAlloc.cpp
  rts/Rendering/Textures/LegacyAtlasAlloc.h
  rts/Rendering/Textures/MultiPageAtlasAlloc.hpp
  rts/Rendering/Textures/QuadtreeAtlasAlloc.h
  rts/Rendering/Textures/RowAtlasAlloc.h
  rts/Rendering/Textures/Texture.cpp
  rts/Rendering/Textures/Texture.hpp
  rts/Rendering/Textures/TextureAtlas.cpp
  rts/Rendering/Textures/TextureAtlas.h
  rts/Sim/Projectiles/ExpGenSpawnable.cpp
  rts/Sim/Projectiles/ExpGenSpawnable.h
  rts/Sim/Projectiles/FireProjectile.cpp
  rts/Sim/Projectiles/FlareProjectile.cpp
  rts/Sim/Projectiles/PieceProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/BeamLaserProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/EmgProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/ExplosiveProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/FireBallProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/FlameProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/LargeBeamLaserProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/LaserProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/LightningProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/MissileProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/StarburstProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/TorpedoProjectile.cpp
  rts/System/float4.h
Labels: status: needs-testing, status: candidate-next

#2408 docs(opengl): Note discrepancy between GL and gl
  rts/Lua/LuaConstGL.cpp
  rts/Lua/LuaOpenGL.cpp
Labels: area: documentation

#2397 Document gl.BindImageTexture parameters
  rts/Lua/LuaOpenGL.cpp
Labels: area: documentation
