Repository beyond-all-reason/RecoilEngine, pull requests merged in 2025-04, with the labels that each got.

#2122 Remove the max time for out of map guards.
  cont/base/springcontent/LuaGadgets/Gadgets/control_guard.lua
  rts/Sim/Units/CommandAI/AirCAI.cpp
  rts/Sim/Units/CommandAI/BuilderCAI.cpp
  rts/Sim/Units/CommandAI/MobileCAI.cpp
  rts/Sim/Units/Unit.cpp
  rts/Sim/Units/Unit.h
Labels: status: candidate

#1901 Fix RmlUi getting blurry when using AA
  rts/Rml/Backends/RmlUi_Renderer_GL3_Recoil.cpp
Labels: area: RmlUi

#2134 Fix /give command position argument.
  rts/Sim/Units/UnitLoader.cpp
Labels: status: candidate

#2179 IUnsyncedActionExecutor processing of ActionRelease events.
  rts/Game/Game.cpp
  rts/Game/UnsyncedActionExecutor.h
  rts/Game/UnsyncedGameCommands.cpp
  rts/Game/UnsyncedGameCommands.h
Labels: area: Input

#2204 Fix fontconfig use after free on game start
  rts/Rendering/Fonts/CFontTexture.cpp
Labels: bug, area: fonts

#2196 Fix for lua stack corruption inside GiveOrder, was missing a return parameter
  rts/Lua/LuaUnsyncedCtrl.cpp
Labels: bug

#2214 Fix GetUnitCurrentCommand negative indexing.
  rts/Lua/LuaSyncedRead.cpp
Labels: bug

#2167 Add Spring.GetMouseButtonsPressed
  rts/Lua/LuaUnsyncedRead.cpp
  rts/Lua/LuaUnsyncedRead.h
Labels: area: Lua API

#2172 Command Documentation Standard
  rts/Lua/LuaConstCMD.cpp
Labels: area: documentation
