Repository beyond-all-reason/RecoilEngine, pull requests merged in 2025-02, with the labels that each got.

#1841 Add Spring.GetSoundDevices.
  rts/Lua/LuaUnsyncedRead.cpp
  rts/Lua/LuaUnsyncedRead.h
  rts/System/Sound/ISound.h
  rts/System/Sound/Null/NullSound.h
  rts/System/Sound/OpenAL/Sound.cpp
  rts/System/Sound/OpenAL/Sound.h
Labels: area: Lua API, status: candidate

#1825 Make SelectedUnitsHandler be a bit smarter about updating.
  rts/Game/SelectedUnitsHandler.cpp
Labels: status: candidate

#1742 Fix leaks inside ProfileDrawer and TimeProfiler.
  rts/Game/UI/ProfileDrawer.cpp
  rts/Game/UI/ProfileDrawer.h
  rts/System/TimeProfiler.cpp
  rts/System/TimeProfiler.h
Labels: area: tools

#1888 Future-proofing for CUnit-derived class sizing
  rts/Sim/Units/UnitHandler.cpp
  rts/Sim/Units/UnitMemPool.h
Labels: status: candidate

#1740 Unloading: extract transportee choice to a function
  rts/Sim/Units/CommandAI/MobileCAI.cpp
Labels: refactor, status: candidate

#1249 Fix landed aircraft starting to fly after being EMP
  rts/Sim/MoveTypes/HoverAirMoveType.cpp
Labels: status: candidate

#1321 Buildpower cache robustness (no logic change)
  rts/Sim/Misc/NanoPieceCache.cpp
  rts/Sim/Misc/NanoPieceCache.h
Labels: status: candidate

#1884 Remove redundant values from StartupScripts
  rts/System/StartScriptGen.cpp
  rts/System/StartScriptGen.h
Labels: status: candidate

#1938 ECS save/load system corrections
  rts/Sim/MoveTypes/Components/MoveTypesComponents.h
  rts/Sim/MoveTypes/GroundMoveType.cpp
  rts/Sim/MoveTypes/Systems/GeneralMoveSystem.cpp
  rts/Sim/MoveTypes/Systems/GroundMoveSystem.cpp
Labels: status: candidate

#1890 Refactor BuilderCAI static caches into new BuilderCaches file.
  rts/Sim/CMakeLists.txt
  rts/Sim/Features/FeatureHandler.cpp
  rts/Sim/Units/CommandAI/BuilderCAI.cpp
  rts/Sim/Units/CommandAI/BuilderCAI.h
  rts/Sim/Units/CommandAI/BuilderCaches.cpp
  rts/Sim/Units/CommandAI/BuilderCaches.h
  rts/Sim/Units/Unit.cpp
  rts/Sim/Units/UnitTypes/Builder.cpp
Labels: refactor, status: candidate

#1851 Controllable AutoShowMetal
  cont/examples/Widgets/gui_autoshowmetal.lua
  rts/Game/UI/GuiHandler.cpp
  rts/Game/UI/GuiHandler.h
  rts/Lua/LuaConstEngine.cpp
  rts/Lua/LuaUnsyncedCtrl.cpp
  rts/Lua/LuaUnsyncedCtrl.h
Labels: area: Lua API

#1289 Move socket.lua into basecontent
  cont/base/springcontent/CMakeLists.txt
  cont/base/springcontent/LuaSocket/socket.lua
  rts/Lua/LuaUI.cpp
  rts/lib/luasocket/CMakeLists.txt
Labels: status: candidate

#1937 Switch push resistant units to use trap check system
  rts/Sim/MoveTypes/GroundMoveType.cpp
  rts/Sim/MoveTypes/Utils/UnitTrapCheckUtils.cpp
  rts/Sim/MoveTypes/Utils/UnitTrapCheckUtils.h
  rts/Sim/Units/UnitDefHandler.cpp
  rts/Sim/Units/UnitDefHandler.h
Labels: status: candidate

#1864 Fix #1698, reverting units to nanoframe via Lua
  rts/Lua/LuaSyncedCtrl.cpp
  rts/Sim/Units/Unit.cpp
  rts/Sim/Units/Unit.h
Labels: status: candidate
