Repository beyond-all-reason/RecoilEngine, pull requests merged in 2025-07, with the labels that each got.

#2428 Fix some docs.
  rts/Lua/LuaSyncedCtrl.cpp
Labels: area: documentation

#2449 refactor(doc): Use emmylua json export for docgen
  .github/workflows/publish-site.yml
  doc/site/assets/css/custom.css
  doc/site/content/_index.md
  doc/site/content/development/writing-site-articles.md
  doc/site/content/docs/lua-api/_index.md
  doc/site/docgen/generator.rb
  doc/site/docgen/templates.rb
  doc/site/emmylua-doc-cli-template/globals_index.md
  doc/site/emmylua-doc-cli-template/index_template.tl
  doc/site/emmylua-doc-cli-template/lua_alias_template.tl
  doc/site/emmylua-doc-cli-template/lua_enum_template.tl
  doc/site/emmylua-doc-cli-template/lua_global_template.tl
  doc/site/emmylua-doc-cli-template/lua_global_template_simple.tl
  doc/site/emmylua-doc-cli-template/lua_module_template.tl
  doc/site/emmylua-doc-cli-template/lua_type_template.tl
  doc/site/emmylua-doc-cli-template/mkdocs_template.tl
  doc/site/emmylua-doc-cli-template/modules_index.md
  doc/site/emmylua-doc-cli-template/types_index.md
  doc/site/layouts/docs/lua_api.html
  doc/site/layouts/partials/entries_sidebar.html
  doc/site/layouts/partials/toc.html
  doc/site/layouts/shortcodes/md.html
  doc/site/mise.ci.toml
  doc/site/mise.toml
  rts/Lua/LuaArchive.cpp
  rts/Lua/LuaConstCMD.cpp
  rts/Lua/LuaConstEngine.cpp
  rts/Lua/LuaFBOs.cpp
  rts/Lua/LuaHandle.cpp
  rts/Lua/LuaHandleSynced.cpp
  rts/Lua/LuaOpenGL.cpp
  rts/Lua/LuaRBOs.cpp
  rts/Lua/LuaShaders.cpp
  rts/Lua/LuaSyncedCtrl.cpp
  rts/Lua/LuaSyncedMoveCtrl.cpp
  rts/Lua/LuaSyncedRead.cpp
  rts/Lua/LuaUnsyncedCtrl.cpp
  rts/Lua/LuaUnsyncedRead.cpp
  rts/Lua/LuaUtils.cpp
  rts/Lua/LuaVBOImpl.cpp
  rts/Lua/LuaVFS.cpp
  rts/Lua/library/Types.lua
  rts/Rml/SolLua/bind/Context.cpp
  rts/Rml/SolLua/bind/DataModel.cpp
  rts/Rml/SolLua/bind/Document.cpp
  rts/Rml/SolLua/bind/Event.cpp
  rts/Rml/SolLua/bind/Global.cpp
Labels: area: documentation

#2417 Add Spring.AddFeatureDamage
  rts/Lua/LuaSyncedCtrl.cpp
  rts/Lua/LuaSyncedCtrl.h
Labels: area: Lua API

#2418 Allow feature destruction on Spring.SetFeatureHealth.
  rts/Lua/LuaSyncedCtrl.cpp
  rts/Lua/LuaSyncedCtrl.h
Labels: area: Lua API

#2436 Lua methods to get/set fireTime/smokeTime for a feature.
  rts/Lua/LuaSyncedCtrl.cpp
  rts/Lua/LuaSyncedCtrl.h
  rts/Lua/LuaSyncedRead.cpp
  rts/Lua/LuaSyncedRead.h
Labels: area: Lua API

#2440 Fix shader docs
  doc/site/content/docs/guides/rendering/making-shaders.md
Labels: area: documentation

#2333 Expose projectile ID in case of beam laser and lightning cannon
  rts/Sim/Weapons/BeamLaser.cpp
  rts/Sim/Weapons/LightningCannon.cpp
Labels: status: candidate-next

#1602 Draft new CEG impact filters: shield and intercepted
  rts/Game/GameHelper.cpp
  rts/Game/GameHelper.h
  rts/Lua/LuaSyncedCtrl.cpp
  rts/Sim/MoveTypes/AAirMoveType.cpp
  rts/Sim/Projectiles/ExpGenSpawner.cpp
  rts/Sim/Projectiles/ExplosionGenerator.cpp
  rts/Sim/Projectiles/ExplosionGenerator.h
  rts/Sim/Projectiles/PieceProjectile.cpp
  rts/Sim/Projectiles/Projectile.h
  rts/Sim/Projectiles/WeaponProjectiles/BeamLaserProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/EmgProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/ExplosiveProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/FireBallProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/FlameProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/LargeBeamLaserProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/LaserProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/LightningProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/MissileProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/StarburstProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/TorpedoProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/WeaponProjectile.cpp
  rts/Sim/Projectiles/WeaponProjectiles/WeaponProjectile.h
  rts/Sim/Units/Scripts/UnitScript.cpp
  rts/Sim/Units/Unit.cpp
  rts/Sim/Weapons/BeamLaser.cpp
  rts/Sim/Weapons/LightningCannon.cpp
  rts/Sim/Weapons/PlasmaRepulser.cpp
Labels: status: needs-testing
